import { readFileSync, writeFileSync } from 'fs';

let c = readFileSync('index.html', 'utf8');

// Step 1: Replace the ENTIRE T object with a properly structured one
const newT = `var T={
  id:{generate:'Generate',cancel:'Batal',prompt:'Masukkan prompt...',negative:'Negative Prompt',settings:'Settings',width:'Width',height:'Height',sampler:'Sampling Method',scheduler:'Scheduler',steps:'Sampling Steps',cfg:'CFG Scale',seed:'Seed',random:'Random',advanced:'Advanced',upscale:'Upscale',fast:'Cepat',normal:'Normal',slow:'Lambat',model:'Model',provider:'Provider',api:'API',login:'Login',logout:'Logout',history:'Riwayat',clear:'Hapus Semua',copy:'Salin',download:'Unduh',delete:'Hapus',close:'Tutup',save:'Simpan',loading:'Memuat...',error:'Error',success:'Berhasil',chat:'Chat',send:'Kirim',typing:'Mengetik...',selectLang:'Bahasa',allImages:'Semua Gambar',image:'Gambar',video:'Video',audio:'Audio',noResults:'Tidak ada hasil',admin:'Panel Admin',pin:'PIN Admin',unlock:'Buka Panel',lock:'Kunci Panel',refresh:'Muat Ulang',audit:'Log Audit',deleteAll:'Hapus Semua',confirmDelete:'Yakin hapus?',yes:'Ya',no:'Tidak',newChat:'Percakapan baru',creative:'Kreatif',faithful:'Setia',instant:'Instan',full:'Lengkap',aspect:'Aspect Ratio',portrait:'Portrait',landscape:'Landscape',square:'Square',custom:'Custom',durasi:'Durasi Animasi',tokens:'Credits',translate:'Terjemahkan?',enhance:'Enhance',addLora:'Tambah LoRA',remove:'Hapus',weight:'Bobot',triggerWords:'Trigger Words',noTrigger:'Tidak ada trigger',vae:'VAE',auto:'Otomatis',defaultValue:'Default',pcOnly:'Hanya PC',mobileOnly:'Hanya HP',desktopMobile:'Desktop & Mobile',collapse:'Tutup',expand:'Buka',pasteData:'Paste Generation Data',presets:'Presets',reset:'Reset',models:'Models',addEmbedding:'Tambah Embedding',addControlNet:'Tambah ControlNet',negativeShort:'Negative',oneImage:'1 gambar',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Belum ada LoRA',noTriggerWords:'Tidak ada trigger'},
  en:{generate:'Generate',cancel:'Cancel',prompt:'Enter prompt...',negative:'Negative Prompt',settings:'Settings',width:'Width',height:'Height',sampler:'Sampling Method',scheduler:'Scheduler',steps:'Sampling Steps',cfg:'CFG Scale',seed:'Seed',random:'Random',advanced:'Advanced',upscale:'Upscale',fast:'Fast',normal:'Normal',slow:'Slow',model:'Model',provider:'Provider',api:'API',login:'Login',logout:'Logout',history:'History',clear:'Clear All',copy:'Copy',download:'Download',delete:'Delete',close:'Close',save:'Save',loading:'Loading...',error:'Error',success:'Success',chat:'Chat',send:'Send',typing:'Typing...',selectLang:'Language',allImages:'All Images',image:'Image',video:'Video',audio:'Audio',noResults:'No results',admin:'Admin Panel',pin:'Admin PIN',unlock:'Unlock Panel',lock:'Lock Panel',refresh:'Refresh',audit:'Audit Log',deleteAll:'Delete All',confirmDelete:'Delete confirm?',yes:'Yes',no:'No',newChat:'New Chat',creative:'Creative',faithful:'Faithful',instant:'Instant',full:'Full',aspect:'Aspect Ratio',portrait:'Portrait',landscape:'Landscape',square:'Square',custom:'Custom',durasi:'Animation Duration',tokens:'Credits',translate:'Translate?',enhance:'Enhance',addLora:'Add LoRA',remove:'Remove',weight:'Weight',triggerWords:'Trigger Words',noTrigger:'No trigger',vae:'VAE',auto:'Auto',defaultValue:'Default',pcOnly:'PC Only',mobileOnly:'Mobile Only',desktopMobile:'Desktop & Mobile',collapse:'Collapse',expand:'Expand',pasteData:'Paste Generation Data',presets:'Presets',reset:'Reset',models:'Models',addEmbedding:'Add Embedding',addControlNet:'Add ControlNet',negativeShort:'Negative',oneImage:'1 image',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'No LoRA yet',noTriggerWords:'No trigger words'},
  ja:{generate:'生成',cancel:'キャンセル',prompt:'プロンプトを入力...',negative:'ネガティブプロンプト',settings:'設定',width:'幅',height:'高さ',sampler:'サンプラー',scheduler:'スケジューラー',steps:'ステップ数',cfg:'CFGスケール',seed:'シード',random:'ランダム',advanced:'詳細',upscale:'アップスケール',fast:'高速',normal:'標準',slow:'低速',model:'モデル',provider:'プロバイダー',api:'API',login:'ログイン',logout:'ログアウト',history:'履歴',clear:'全削除',copy:'コピー',download:'ダウンロード',delete:'削除',close:'閉じる',save:'保存',loading:'読み込み中...',error:'エラー',success:'成功',chat:'チャット',send:'送信',typing:'入力中...',selectLang:'言語',allImages:'すべての画像',image:'画像',video:'動画',audio:'音声',noResults:'結果なし',admin:'管理パネル',pin:'管理PIN',unlock:'ロック解除',lock:'ロック',refresh:'更新',audit:'監査ログ',deleteAll:'全削除',confirmDelete:'削除しますか？',yes:'はい',no:'いいえ',newChat:'新しいチャット',creative:'クリエイティブ',faithful:'忠実',instant:'即時',full:'完全',aspect:'アスペクト比',portrait:'縦長',landscape:'横長',square:'正方形',custom:'カスタム',durasi:'アニメーション時間',tokens:'クレジット',translate:'翻訳？',enhance:'エンハンス',addLora:'LoRA追加',remove:'削除',weight:'ウェイト',triggerWords:'トリガーワード',noTrigger:'トリガーなし',vae:'VAE',auto:'自動',defaultValue:'デフォルト',pcOnly:'PCのみ',mobileOnly:'モバイルのみ',desktopMobile:'デスクトップ＆モバイル',collapse:'折りたたむ',expand:'展開',pasteData:'生成データ貼り付け',presets:'プリセット',reset:'リセット',models:'モデル',addEmbedding:'埋め込み追加',addControlNet:'ControlNet追加',negativeShort:'ネガティブ',oneImage:'1枚',samplerLabel:'サンプラー',schedulerLabel:'スケジューラー',noLora:'LoRAなし',noTriggerWords:'トリガーなし'},
  ko:{generate:'생성',cancel:'취소',prompt:'프롬프트 입력...',negative:'네거티브 프롬프트',settings:'설정',width:'너비',height:'높이',sampler:'샘플러',scheduler:'스케줄러',steps:'스텝 수',cfg:'CFG 스케일',seed:'시드',random:'랜덤',advanced:'고급',upscale:'업스케일',fast:'빠름',normal:'보통',slow:'느림',model:'모델',provider:'프로바이더',api:'API',login:'로그인',logout:'로그아웃',history:'기록',clear:'전체 삭제',copy:'복사',download:'다운로드',delete:'삭제',close:'닫기',save:'저장',loading:'로딩 중...',error:'오류',success:'성공',chat:'채팅',send:'보내기',typing:'입력 중...',selectLang:'언어',allImages:'모든 이미지',image:'이미지',video:'비디오',audio:'오디오',noResults:'결과 없음',admin:'관리자 패널',pin:'관리자 PIN',unlock:'잠금 해제',lock:'잠금',refresh:'새로고침',audit:'감사 로그',deleteAll:'전체 삭제',confirmDelete:'삭제하시겠습니까?',yes:'예',no:'아니오',newChat:'새 채팅',creative:'크리에이티브',faithful:'충실',instant:'즉시',full:'전체',aspect:'화면 비율',portrait:'세로',landscape:'가로',square:'정사각형',custom:'사용자 정의',durasi:'애니메이션 시간',tokens:'크레딧',translate:'번역?',enhance:'강화',addLora:'LoRA 추가',remove:'제거',weight:'가중치',triggerWords:'트리거 워드',noTrigger:'트리거 없음',vae:'VAE',auto:'자동',defaultValue:'기본값',pcOnly:'PC 전용',mobileOnly:'모바일 전용',desktopMobile:'데스크톱 & 모바일',collapse:'접기',expand:'펼치기',pasteData:'생성 데이터 붙여넣기',presets:'프리셋',reset:'초기화',models:'모델',addEmbedding:'임베딩 추가',addControlNet:'ControlNet 추가',negativeShort:'네거티브',oneImage:'1장',samplerLabel:'샘플러',schedulerLabel:'스케줄러',noLora:'LoRA 없음',noTriggerWords:'트리거 없음'},
  zh:{generate:'生成',cancel:'取消',prompt:'输入提示词...',negative:'负面提示词',settings:'设置',width:'宽度',height:'高度',sampler:'采样器',scheduler:'调度器',steps:'步数',cfg:'CFG缩放',seed:'种子',random:'随机',advanced:'高级',upscale:'放大',fast:'快速',normal:'标准',slow:'慢速',model:'模型',provider:'提供商',api:'API',login:'登录',logout:'退出',history:'历史',clear:'清空',copy:'复制',download:'下载',delete:'删除',close:'关闭',save:'保存',loading:'加载中...',error:'错误',success:'成功',chat:'聊天',send:'发送',typing:'输入中...',selectLang:'语言',allImages:'所有图片',image:'图片',video:'视频',audio:'音频',noResults:'无结果',admin:'管理面板',pin:'管理PIN',unlock:'解锁面板',lock:'锁定面板',refresh:'刷新',audit:'审计日志',deleteAll:'删除全部',confirmDelete:'确认删除？',yes:'是',no:'否',newChat:'新对话',creative:'创意',faithful:'忠实',instant:'即时',full:'完整',aspect:'宽高比',portrait:'竖屏',landscape:'横屏',square:'正方形',custom:'自定义',durasi:'动画时长',tokens:'积分',translate:'翻译？',enhance:'增强',addLora:'添加LoRA',remove:'移除',weight:'权重',triggerWords:'触发词',noTrigger:'无触发词',vae:'VAE',auto:'自动',defaultValue:'默认',pcOnly:'仅PC',mobileOnly:'仅移动端',desktopMobile:'桌面端和移动端',collapse:'折叠',expand:'展开',pasteData:'粘贴生成数据',presets:'预设',reset:'重置',models:'模型',addEmbedding:'添加嵌入',addControlNet:'添加ControlNet',negativeShort:'负面',oneImage:'1张',samplerLabel:'采样器',schedulerLabel:'调度器',noLora:'暂无LoRA',noTriggerWords:'无触发词'},
  es:{generate:'Generar',cancel:'Cancelar',prompt:'Escribe un prompt...',negative:'Prompt Negativo',settings:'Ajustes',width:'Ancho',height:'Alto',sampler:'Método de Muestreo',scheduler:'Programador',steps:'Pasos',cfg:'Escala CFG',seed:'Semilla',random:'Aleatorio',advanced:'Avanzado',upscale:'Escalar',fast:'Rápido',normal:'Normal',slow:'Lento',model:'Modelo',provider:'Proveedor',api:'API',login:'Iniciar sesión',logout:'Cerrar sesión',history:'Historial',clear:'Borrar todo',copy:'Copiar',download:'Descargar',delete:'Eliminar',close:'Cerrar',save:'Guardar',loading:'Cargando...',error:'Error',success:'Éxito',chat:'Chat',send:'Enviar',typing:'Escribiendo...',selectLang:'Idioma',allImages:'Todas las imágenes',image:'Imagen',video:'Video',audio:'Audio',noResults:'Sin resultados',admin:'Panel Admin',pin:'PIN Admin',unlock:'Desbloquear',lock:'Bloquear',refresh:'Actualizar',audit:'Registro',deleteAll:'Eliminar todo',confirmDelete:'¿Eliminar?',yes:'Sí',no:'No',newChat:'Nuevo chat',creative:'Creativo',faithful:'Fiel',instant:'Instantáneo',full:'Completo',aspect:'Relación de Aspecto',portrait:'Vertical',landscape:'Horizontal',square:'Cuadrado',custom:'Personalizado',durasi:'Duración',tokens:'Créditos',translate:'¿Traducir?',enhance:'Mejorar',addLora:'Añadir LoRA',remove:'Quitar',weight:'Peso',triggerWords:'Palabras Clave',noTrigger:'Sin trigger',vae:'VAE',auto:'Automático',defaultValue:'Predeterminado',pcOnly:'Solo PC',mobileOnly:'Solo Móvil',desktopMobile:'Escritorio y Móvil',collapse:'Colapsar',expand:'Expandir',pasteData:'Pegar Datos',presets:'Preajustes',reset:'Reiniciar',models:'Modelos',addEmbedding:'Añadir Embedding',addControlNet:'Añadir ControlNet',negativeShort:'Negativo',oneImage:'1 imagen',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Sin LoRA',noTriggerWords:'Sin trigger words'},
  fr:{generate:'Générer',cancel:'Annuler',prompt:'Entrez un prompt...',negative:'Prompt Négatif',settings:'Paramètres',width:'Largeur',height:'Hauteur',sampler:'Méthode d\\'échantillonnage',scheduler:'Planificateur',steps:'Étapes',cfg:'Échelle CFG',seed:'Graine',random:'Aléatoire',advanced:'Avancé',upscale:'Agrandir',fast:'Rapide',normal:'Normal',slow:'Lent',model:'Modèle',provider:'Fournisseur',api:'API',login:'Connexion',logout:'Déconnexion',history:'Historique',clear:'Tout supprimer',copy:'Copier',download:'Télécharger',delete:'Supprimer',close:'Fermer',save:'Enregistrer',loading:'Chargement...',error:'Erreur',success:'Succès',chat:'Chat',send:'Envoyer',typing:'En train d\\'écrire...',selectLang:'Langue',allImages:'Toutes les images',image:'Image',video:'Vidéo',audio:'Audio',noResults:'Aucun résultat',admin:'Panneau Admin',pin:'PIN Admin',unlock:'Déverrouiller',lock:'Verrouiller',refresh:'Actualiser',audit:'Journal',deleteAll:'Tout supprimer',confirmDelete:'Supprimer ?',yes:'Oui',no:'Non',newChat:'Nouveau chat',creative:'Créatif',faithful:'Fidèle',instant:'Instantané',full:'Complet',aspect:'Ratio d\\'aspect',portrait:'Portrait',landscape:'Paysage',square:'Carré',custom:'Personnalisé',durasi:'Durée',tokens:'Crédits',translate:'Traduire ?',enhance:'Améliorer',addLora:'Ajouter LoRA',remove:'Retirer',weight:'Poids',triggerWords:'Mots déclencheurs',noTrigger:'Sans trigger',vae:'VAE',auto:'Automatique',defaultValue:'Défaut',pcOnly:'PC uniquement',mobileOnly:'Mobile uniquement',desktopMobile:'Bureau et Mobile',collapse:'Réduire',expand:'Développer',pasteData:'Coller les données',presets:'Préréglages',reset:'Réinitialiser',models:'Modèles',addEmbedding:'Ajouter Embedding',addControlNet:'Ajouter ControlNet',negativeShort:'Négatif',oneImage:'1 image',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Pas de LoRA',noTriggerWords:'Pas de trigger words'},
  de:{generate:'Generieren',cancel:'Abbrechen',prompt:'Prompt eingeben...',negative:'Negativer Prompt',settings:'Einstellungen',width:'Breite',height:'Höhe',sampler:'Sampling-Methode',scheduler:'Scheduler',steps:'Schritte',cfg:'CFG-Skala',seed:'Seed',random:'Zufällig',advanced:'Erweitert',upscale:'Hochskalieren',fast:'Schnell',normal:'Normal',slow:'Langsam',model:'Modell',provider:'Anbieter',api:'API',login:'Anmelden',logout:'Abmelden',history:'Verlauf',clear:'Alle löschen',copy:'Kopieren',download:'Herunterladen',delete:'Löschen',close:'Schließen',save:'Speichern',loading:'Laden...',error:'Fehler',success:'Erfolg',chat:'Chat',send:'Senden',typing:'Schreibt...',selectLang:'Sprache',allImages:'Alle Bilder',image:'Bild',video:'Video',audio:'Audio',noResults:'Keine Ergebnisse',admin:'Admin-Panel',pin:'Admin-PIN',unlock:'Entsperren',lock:'Sperren',refresh:'Aktualisieren',audit:'Audit-Log',deleteAll:'Alle löschen',confirmDelete:'Löschen?',yes:'Ja',no:'Nein',newChat:'Neuer Chat',creative:'Kreativ',faithful:'Treue',instant:'Sofort',full:'Vollständig',aspect:'Seitenverhältnis',portrait:'Hochformat',landscape:'Querformat',square:'Quadrat',custom:'Benutzerdefiniert',durasi:'Dauer',tokens:'Guthaben',translate:'Übersetzen?',enhance:'Verbessern',addLora:'LoRA hinzufügen',remove:'Entfernen',weight:'Gewicht',triggerWords:'Trigger-Wörter',noTrigger:'Kein Trigger',vae:'VAE',auto:'Automatisch',defaultValue:'Standard',pcOnly:'Nur PC',mobileOnly:'Nur Mobil',desktopMobile:'Desktop & Mobil',collapse:'Einklappen',expand:'Ausklappen',pasteData:'Daten einfügen',presets:'Voreinstellungen',reset:'Zurücksetzen',models:'Modelle',addEmbedding:'Embedding hinzufügen',addControlNet:'ControlNet hinzufügen',negativeShort:'Negativ',oneImage:'1 Bild',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Keine LoRA',noTriggerWords:'Keine Trigger-Wörter'},
  pt:{generate:'Gerar',cancel:'Cancelar',prompt:'Digite um prompt...',negative:'Prompt Negativo',settings:'Configurações',width:'Largura',height:'Altura',sampler:'Método de Amostragem',scheduler:'Agendador',steps:'Passos',cfg:'Escala CFG',seed:'Semente',random:'Aleatório',advanced:'Avançado',upscale:'Escalar',fast:'Rápido',normal:'Normal',slow:'Lento',model:'Modelo',provider:'Provedor',api:'API',login:'Entrar',logout:'Sair',history:'Histórico',clear:'Limpar tudo',copy:'Copiar',download:'Baixar',delete:'Excluir',close:'Fechar',save:'Salvar',loading:'Carregando...',error:'Erro',success:'Sucesso',chat:'Chat',send:'Enviar',typing:'Digitando...',selectLang:'Idioma',allImages:'Todas as imagens',image:'Imagem',video:'Vídeo',audio:'Áudio',noResults:'Sem resultados',admin:'Painel Admin',pin:'PIN Admin',unlock:'Desbloquear',lock:'Bloquear',refresh:'Atualizar',audit:'Registro',deleteAll:'Excluir tudo',confirmDelete:'Excluir?',yes:'Sim',no:'Não',newChat:'Novo chat',creative:'Criativo',faithful:'Fiel',instant:'Instantâneo',full:'Completo',aspect:'Proporção',portrait:'Retrato',landscape:'Paisagem',square:'Quadrado',custom:'Personalizado',durasi:'Duração',tokens:'Créditos',translate:'Traduzir?',enhance:'Aprimorar',addLora:'Adicionar LoRA',remove:'Remover',weight:'Peso',triggerWords:'Palavras-chave',noTrigger:'Sem trigger',vae:'VAE',auto:'Automático',defaultValue:'Padrão',pcOnly:'Apenas PC',mobileOnly:'Apenas Celular',desktopMobile:'Desktop e Celular',collapse:'Recolher',expand:'Expandir',pasteData:'Colar dados',presets:'Predefinições',reset:'Redefinir',models:'Modelos',addEmbedding:'Adicionar Embedding',addControlNet:'Adicionar ControlNet',negativeShort:'Negativo',oneImage:'1 imagem',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Sem LoRA',noTriggerWords:'Sem trigger words'},
  ru:{generate:'Создать',cancel:'Отмена',prompt:'Введите промпт...',negative:'Негативный промпт',settings:'Настройки',width:'Ширина',height:'Высота',sampler:'Метод сэмплинга',scheduler:'Планировщик',steps:'Шаги',cfg:'Масштаб CFG',seed:'Зерно',random:'Случайно',advanced:'Расширенные',upscale:'Масштабирование',fast:'Быстро',normal:'Обычно',slow:'Медленно',model:'Модель',provider:'Провайдер',api:'API',login:'Войти',logout:'Выйти',history:'История',clear:'Очистить',copy:'Копировать',download:'Скачать',delete:'Удалить',close:'Закрыть',save:'Сохранить',loading:'Загрузка...',error:'Ошибка',success:'Успех',chat:'Чат',send:'Отправить',typing:'Печатает...',selectLang:'Язык',allImages:'Все изображения',image:'Изображение',video:'Видео',audio:'Аудио',noResults:'Нет результатов',admin:'Панель админа',pin:'PIN админа',unlock:'Разблокировать',lock:'Заблокировать',refresh:'Обновить',audit:'Журнал',deleteAll:'Удалить всё',confirmDelete:'Удалить?',yes:'Да',no:'Нет',newChat:'Новый чат',creative:'Креативный',faithful:'Верный',instant:'Мгновенно',full:'Полный',aspect:'Соотношение сторон',portrait:'Портрет',landscape:'Пейзаж',square:'Квадрат',custom:'Пользовательский',durasi:'Длительность',tokens:'Кредиты',translate:'Перевести?',enhance:'Улучшить',addLora:'Добавить LoRA',remove:'Удалить',weight:'Вес',triggerWords:'Триггерные слова',noTrigger:'Без триггера',vae:'VAE',auto:'Авто',defaultValue:'По умолчанию',pcOnly:'Только ПК',mobileOnly:'Только мобильный',desktopMobile:'ПК и мобильный',collapse:'Свернуть',expand:'Развернуть',pasteData:'Вставить данные',presets:'Пресеты',reset:'Сбросить',models:'Модели',addEmbedding:'Добавить Embedding',addControlNet:'Добавить ControlNet',negativeShort:'Негатив',oneImage:'1 изображение',samplerLabel:'Сэмплер',schedulerLabel:'Планировщик',noLora:'Нет LoRA',noTriggerWords:'Нет триггерных слов'},
  ar:{generate:'توليد',cancel:'إلغاء',prompt:'أدخل البرومبت...',negative:'برومبت سلبي',settings:'الإعدادات',width:'العرض',height:'الارتفاع',sampler:'طريقة أخذ العينات',scheduler:'المجدول',steps:'الخطوات',cfg:'مقياس CFG',seed:'البذرة',random:'عشوائي',advanced:'متقدم',upscale:'تكبير',fast:'سريع',normal:'عادي',slow:'بطيء',model:'النموذج',provider:'المزود',api:'API',login:'تسجيل الدخول',logout:'تسجيل الخروج',history:'السجل',clear:'مسح الكل',copy:'نسخ',download:'تحميل',delete:'حذف',close:'إغلاق',save:'حفظ',loading:'جاري التحميل...',error:'خطأ',success:'نجاح',chat:'دردشة',send:'إرسال',typing:'يكتب...',selectLang:'اللغة',allImages:'جميع الصور',image:'صورة',video:'فيديو',audio:'صوت',noResults:'لا نتائج',admin:'لوحة الإدارة',pin:'PIN الإدارة',unlock:'فتح القفل',lock:'قفل',refresh:'تحديث',audit:'سجل التدقيق',deleteAll:'حذف الكل',confirmDelete:'تأكيد الحذف؟',yes:'نعم',no:'لا',newChat:'محادثة جديدة',creative:'إبداعي',faithful:'وفي',instant:'فوري',full:'كامل',aspect:'نسبة العرض',portrait:'عمودي',landscape:'أفقي',square:'مربع',custom:'مخصص',durasi:'المدة',tokens:'ائتمانات',translate:'ترجمة؟',enhance:'تحسين',addLora:'إضافة LoRA',remove:'إزالة',weight:'الوزن',triggerWords:'كلمات المحفز',noTrigger:'بدون محفز',vae:'VAE',auto:'تلقائي',defaultValue:'افتراضي',pcOnly:'كمبيوتر فقط',mobileOnly:'محمول فقط',desktopMobile:'كمبيوتر ومحمول',collapse:'طي',expand:'توسيع',pasteData:'لصق البيانات',presets:'الإعدادات المسبقة',reset:'إعادة تعيين',models:'النماذج',addEmbedding:'إضافة Embedding',addControlNet:'إضافة ControlNet',negativeShort:'سلبي',oneImage:'1 صورة',samplerLabel:'العاينة',schedulerLabel:'المجدول',noLora:'لا يوجد LoRA',noTriggerWords:'لا توجد كلمات محفزة'},
  hi:{generate:'जनरेट',cancel:'रद्द करें',prompt:'प्रॉम्प्ट दर्ज करें...',negative:'नेगेटिव प्रॉम्प्ट',settings:'सेटिंग्स',width:'चौड़ाई',height:'ऊँचाई',sampler:'सैम्पलिंग विधि',scheduler:'शेड्यूलर',steps:'स्टेप्स',cfg:'CFG स्केल',seed:'सीड',random:'यादृच्छिक',advanced:'उन्नत',upscale:'अपस्केल',fast:'तेज़',normal:'सामान्य',slow:'धीमा',model:'मॉडल',provider:'प्रदाता',api:'API',login:'लॉगिन',logout:'लॉगआउट',history:'इतिहास',clear:'सब मिटाएं',copy:'कॉपी',download:'डाउनलोड',delete:'हटाएं',close:'बंद करें',save:'सहेजें',loading:'लोड हो रहा है...',error:'त्रुटि',success:'सफल',chat:'चैट',send:'भेजें',typing:'टाइप हो रहा है...',selectLang:'भाषा',allImages:'सभी चित्र',image:'चित्र',video:'वीडियो',audio:'ऑडियो',noResults:'कोई परिणाम नहीं',admin:'एडमिन पैनल',pin:'एडमिन PIN',unlock:'अनलॉक',lock:'लॉक',refresh:'रीफ्रेश',audit:'ऑडिट लॉग',deleteAll:'सब हटाएं',confirmDelete:'हटाएं?',yes:'हाँ',no:'नहीं',newChat:'नई चैट',creative:'रचनात्मक',faithful:'वफादार',instant:'तुरंत',full:'पूर्ण',aspect:'आस्पेक्ट रेश्यो',portrait:'पोर्ट्रेट',landscape:'लैंडस्केप',square:'वर्ग',custom:'कस्टम',durasi:'अवधि',tokens:'क्रेडिट',translate:'अनुवाद?',enhance:'बेहतर बनाएं',addLora:'LoRA जोड़ें',remove:'हटाएं',weight:'वज़न',triggerWords:'ट्रिगर शब्द',noTrigger:'ट्रिगर नहीं',vae:'VAE',auto:'स्वचालित',defaultValue:'डिफ़ॉल्ट',pcOnly:'केवल PC',mobileOnly:'केवल मोबाइल',desktopMobile:'डेस्कटॉप और मोबाइल',collapse:'संक्षिप्त',expand:'विस्तृत',pasteData:'डेटा पेस्ट करें',presets:'प्रीसेट',reset:'रीसेट',models:'मॉडल',addEmbedding:'Embedding जोड़ें',addControlNet:'ControlNet जोड़ें',negativeShort:'नेगेटिव',oneImage:'1 चित्र',samplerLabel:'सैम्पलर',schedulerLabel:'शेड्यूलर',noLora:'कोई LoRA नहीं',noTriggerWords:'कोई ट्रिगर शब्द नहीं'},
  th:{generate:'สร้าง',cancel:'ยกเลิก',prompt:'ป้อนพรอมต์...',negative:'พรอมต์เชิงลบ',settings:'ตั้งค่า',width:'ความกว้าง',height:'ความสูง',sampler:'วิธีการสุ่ม',scheduler:'ตัวจัดตาราง',steps:'จำนวนขั้นตอน',cfg:'มาตราส่วน CFG',seed:'เมล็ด',random:'สุ่ม',advanced:'ขั้นสูง',upscale:'ขยาย',fast:'เร็ว',normal:'ปกติ',slow:'ช้า',model:'โมเดล',provider:'ผู้ให้บริการ',api:'API',login:'เข้าสู่ระบบ',logout:'ออกจากระบบ',history:'ประวัติ',clear:'ล้างทั้งหมด',copy:'คัดลอก',download:'ดาวน์โหลด',delete:'ลบ',close:'ปิด',save:'บันทึก',loading:'กำลังโหลด...',error:'ข้อผิดพลาด',success:'สำเร็จ',chat:'แชท',send:'ส่ง',typing:'กำลังพิมพ์...',selectLang:'ภาษา',allImages:'รูปภาพทั้งหมด',image:'รูปภาพ',video:'วิดีโอ',audio:'เสียง',noResults:'ไม่มีผลลัพธ์',admin:'แผงจัดการ',pin:'PIN ผู้ดูแล',unlock:'ปลดล็อก',lock:'ล็อก',refresh:'รีเฟรช',audit:'บันทึกการตรวจสอบ',deleteAll:'ลบทั้งหมด',confirmDelete:'ยืนยันการลบ?',yes:'ใช่',no:'ไม่',newChat:'แชทใหม่',creative:'สร้างสรรค์',faithful:'ซื่อสัตย์',instant:'ทันที',full:'เต็ม',aspect:'สัดส่วนภาพ',portrait:'แนวตั้ง',landscape:'แนวนอน',square:'สี่เหลี่ยมจัตุรัส',custom:'กำหนดเอง',durasi:'ระยะเวลา',tokens:'เครดิต',translate:'แปล?',enhance:'ปรับปรุง',addLora:'เพิ่ม LoRA',remove:'ลบ',weight:'น้ำหนัก',triggerWords:'คำทริกเกอร์',noTrigger:'ไม่มีทริกเกอร์',vae:'VAE',auto:'อัตโนมัติ',defaultValue:'ค่าเริ่มต้น',pcOnly:'เฉพาะ PC',mobileOnly:'เฉพาะมือถือ',desktopMobile:'เดสก์ท็อปและมือถือ',collapse:'ย่อ',expand:'ขยาย',pasteData:'วางข้อมูล',presets:'พรีเซ็ต',reset:'รีเซ็ต',models:'โมเดล',addEmbedding:'เพิ่ม Embedding',addControlNet:'เพิ่ม ControlNet',negativeShort:'เชิงลบ',oneImage:'1 รูป',samplerLabel:'ตัวสุ่ม',schedulerLabel:'ตัวจัดตาราง',noLora:'ยังไม่มี LoRA',noTriggerWords:'ไม่มีคำทริกเกอร์'},
  vi:{generate:'Tạo',cancel:'Hủy',prompt:'Nhập prompt...',negative:'Prompt âm',settings:'Cài đặt',width:'Chiều rộng',height:'Chiều cao',sampler:'Phương pháp lấy mẫu',scheduler:'Lên lịch',steps:'Bước',cfg:'Tỷ lệ CFG',seed:'Hạt giống',random:'Ngẫu nhiên',advanced:'Nâng cao',upscale:'Phóng to',fast:'Nhanh',normal:'Bình thường',slow:'Chậm',model:'Mô hình',provider:'Nhà cung cấp',api:'API',login:'Đăng nhập',logout:'Đăng xuất',history:'Lịch sử',clear:'Xóa tất cả',copy:'Sao chép',download:'Tải xuống',delete:'Xóa',close:'Đóng',save:'Lưu',loading:'Đang tải...',error:'Lỗi',success:'Thành công',chat:'Trò chuyện',send:'Gửi',typing:'Đang nhập...',selectLang:'Ngôn ngữ',allImages:'Tất cả hình ảnh',image:'Hình ảnh',video:'Video',audio:'Âm thanh',noResults:'Không có kết quả',admin:'Bảng quản trị',pin:'PIN quản trị',unlock:'Mở khóa',lock:'Khóa',refresh:'Làm mới',audit:'Nhật ký',deleteAll:'Xóa tất cả',confirmDelete:'Xóa?',yes:'Có',no:'Không',newChat:'Cuộc trò chuyện mới',creative:'Sáng tạo',faithful:'Trung thành',instant:'Tức thì',full:'Đầy đủ',aspect:'Tỷ lệ khung hình',portrait:'Dọc',landscape:'Ngang',square:'Vuông',custom:'Tùy chỉnh',durasi:'Thời lượng',tokens:'Tín dụng',translate:'Dịch?',enhance:'Cải thiện',addLora:'Thêm LoRA',remove:'Bỏ',weight:'Trọng số',triggerWords:'Từ kích hoạt',noTrigger:'Không có trigger',vae:'VAE',auto:'Tự động',defaultValue:'Mặc định',pcOnly:'Chỉ PC',mobileOnly:'Chỉ điện thoại',desktopMobile:'Máy tính & Điện thoại',collapse:'Thu gọn',expand:'Mở rộng',pasteData:'Dán dữ liệu',presets:'Mẫu sẵn',reset:'Đặt lại',models:'Mô hình',addEmbedding:'Thêm Embedding',addControlNet:'Thêm ControlNet',negativeShort:'Âm',oneImage:'1 ảnh',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Chưa có LoRA',noTriggerWords:'Không có trigger words'},
  tr:{generate:'Oluştur',cancel:'İptal',prompt:'Prompt girin...',negative:'Negatif Prompt',settings:'Ayarlar',width:'Genişlik',height:'Yükseklik',sampler:'Örnekleme Yöntemi',scheduler:'Zamanlayıcı',steps:'Adımlar',cfg:'CFG Ölçeği',seed:'Tohum',random:'Rastgele',advanced:'Gelişmiş',upscale:'Ölçeklendir',fast:'Hızlı',normal:'Normal',slow:'Yavaş',model:'Model',provider:'Sağlayıcı',api:'API',login:'Giriş',logout:'Çıkış',history:'Geçmiş',clear:'Tümünü Temizle',copy:'Kopyala',download:'İndir',delete:'Sil',close:'Kapat',save:'Kaydet',loading:'Yükleniyor...',error:'Hata',success:'Başarılı',chat:'Sohbet',send:'Gönder',typing:'Yazıyor...',selectLang:'Dil',allImages:'Tüm Görseller',image:'Görsel',video:'Video',audio:'Ses',noResults:'Sonuç yok',admin:'Yönetici Paneli',pin:'Yönetici PIN',unlock:'Kilidi Aç',lock:'Kilitle',refresh:'Yenile',audit:'Denetim Günlüğü',deleteAll:'Tümünü Sil',confirmDelete:'Sil?',yes:'Evet',no:'Hayır',newChat:'Yeni Sohbet',creative:'Yaratıcı',faithful:'Sadık',instant:'Anında',full:'Tam',aspect:'En Boy Oranı',portrait:'Dikey',landscape:'Yatay',square:'Kare',custom:'Özel',durasi:'Süre',tokens:'Kredi',translate:'Çevir?',enhance:'Geliştir',addLora:'LoRA Ekle',remove:'Kaldır',weight:'Ağırlık',triggerWords:'Tetikleyici Kelimeler',noTrigger:'Tetikleyici Yok',vae:'VAE',auto:'Otomatik',defaultValue:'Varsayılan',pcOnly:'Yalnızca PC',mobileOnly:'Yalnızca Mobil',desktopMobile:'Masaüstü & Mobil',collapse:'Daralt',expand:'Genişlet',pasteData:'Veri Yapıştır',presets:'Ön Ayarlar',reset:'Sıfırla',models:'Modeller',addEmbedding:'Embedding Ekle',addControlNet:'ControlNet Ekle',negativeShort:'Negatif',oneImage:'1 görsel',samplerLabel:'Örnekleme',schedulerLabel:'Zamanlayıcı',noLora:'LoRA Yok',noTriggerWords:'Tetikleyici Kelime Yok'},
  pl:{generate:'Generuj',cancel:'Anuluj',prompt:'Wpisz prompt...',negative:'Prompt Negatywny',settings:'Ustawienia',width:'Szerokość',height:'Wysokość',sampler:'Metoda Próbkowania',scheduler:'Planista',steps:'Kroki',cfg:'Skala CFG',seed:'Ziarno',random:'Losowy',advanced:'Zaawansowane',upscale:'Powiększ',fast:'Szybki',normal:'Normalny',slow:'Wolny',model:'Model',provider:'Dostawca',api:'API',login:'Zaloguj',logout:'Wyloguj',history:'Historia',clear:'Wyczyść wszystko',copy:'Kopiuj',download:'Pobierz',delete:'Usuń',close:'Zamknij',save:'Zapisz',loading:'Ładowanie...',error:'Błąd',success:'Sukces',chat:'Czat',send:'Wyślij',typing:'Pisanie...',selectLang:'Język',allImages:'Wszystkie obrazy',image:'Obraz',video:'Wideo',audio:'Audio',noResults:'Brak wyników',admin:'Panel Admina',pin:'PIN Admina',unlock:'Odblokuj',lock:'Zablokuj',refresh:'Odśwież',audit:'Dziennik',deleteAll:'Usuń wszystko',confirmDelete:'Usuń?',yes:'Tak',no:'Nie',newChat:'Nowy czat',creative:'Kreatywny',faithful:'Wierny',instant:'Natychmiast',full:'Pełny',aspect:'Proporcje',portrait:'Portret',landscape:'Krajobraz',square:'Kwadrat',custom:'Niestandardowy',durasi:'Czas trwania',tokens:'Kredyty',translate:'Tłumaczyć?',enhance:'Ulepsz',addLora:'Dodaj LoRA',remove:'Usuń',weight:'Waga',triggerWords:'Słowa wyzwalacze',noTrigger:'Brak wyzwalacza',vae:'VAE',auto:'Automatyczne',defaultValue:'Domyślne',pcOnly:'Tylko PC',mobileOnly:'Tylko mobilny',desktopMobile:'Desktop i mobilny',collapse:'Zwiń',expand:'Rozwiń',pasteData:'Wklej dane',presets:'Presety',reset:'Resetuj',models:'Modele',addEmbedding:'Dodaj Embedding',addControlNet:'Dodaj ControlNet',negativeShort:'Negatywny',oneImage:'1 obraz',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Brak LoRA',noTriggerWords:'Brak słów wyzwalaczy'},
  nl:{generate:'Genereer',cancel:'Annuleren',prompt:'Voer prompt in...',negative:'Negatieve Prompt',settings:'Instellingen',width:'Breedte',height:'Hoogte',sampler:'Sampling Methode',scheduler:'Scheduler',steps:'Stappen',cfg:'CFG Schaal',seed:'Seed',random:'Willekeurig',advanced:'Geavanceerd',upscale:'Opschalen',fast:'Snel',normal:'Normaal',slow:'Langzaam',model:'Model',provider:'Provider',api:'API',login:'Inloggen',logout:'Uitloggen',history:'Geschiedenis',clear:'Alles wissen',copy:'Kopiëren',download:'Downloaden',delete:'Verwijderen',close:'Sluiten',save:'Opslaan',loading:'Laden...',error:'Fout',success:'Succes',chat:'Chat',send:'Versturen',typing:'Typen...',selectLang:'Taal',allImages:'Alle afbeeldingen',image:'Afbeelding',video:'Video',audio:'Audio',noResults:'Geen resultaten',admin:'Admin Paneel',pin:'Admin PIN',unlock:'Ontgrendelen',lock:'Vergrendelen',refresh:'Vernieuwen',audit:'Audit Log',deleteAll:'Alles verwijderen',confirmDelete:'Verwijderen?',yes:'Ja',no:'Nee',newChat:'Nieuwe chat',creative:'Creatief',faithful:'Getrouw',instant:'Direct',full:'Volledig',aspect:'Beeldverhouding',portrait:'Staand',landscape:'Liggend',square:'Vierkant',custom:'Aangepast',durasi:'Duur',tokens:'Tegoed',translate:'Vertalen?',enhance:'Verbeteren',addLora:'LoRA toevoegen',remove:'Verwijderen',weight:'Gewicht',triggerWords:'Trigger Woorden',noTrigger:'Geen trigger',vae:'VAE',auto:'Automatisch',defaultValue:'Standaard',pcOnly:'Alleen PC',mobileOnly:'Alleen mobiel',desktopMobile:'Desktop & mobiel',collapse:'Inklappen',expand:'Uitklappen',pasteData:'Data plakken',presets:'Voorinstellingen',reset:'Resetten',models:'Modellen',addEmbedding:'Embedding toevoegen',addControlNet:'ControlNet toevoegen',negativeShort:'Negatief',oneImage:'1 afbeelding',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Geen LoRA',noTriggerWords:'Geen trigger woorden'},
  it:{generate:'Genera',cancel:'Annulla',prompt:'Inserisci prompt...',negative:'Prompt Negativo',settings:'Impostazioni',width:'Larghezza',height:'Altezza',sampler:'Metodo di Campionamento',scheduler:'Scheduler',steps:'Passi',cfg:'Scala CFG',seed:'Seme',random:'Casuale',advanced:'Avanzato',upscale:'Ingrandisci',fast:'Veloce',normal:'Normale',slow:'Lento',model:'Modello',provider:'Provider',api:'API',login:'Accedi',logout:'Esci',history:'Cronologia',clear:'Cancella tutto',copy:'Copia',download:'Scarica',delete:'Elimina',close:'Chiudi',save:'Salva',loading:'Caricamento...',error:'Errore',success:'Successo',chat:'Chat',send:'Invia',typing:'Scrivendo...',selectLang:'Lingua',allImages:'Tutte le immagini',image:'Immagine',video:'Video',audio:'Audio',noResults:'Nessun risultato',admin:'Pannello Admin',pin:'PIN Admin',unlock:'Sblocca',lock:'Blocca',refresh:'Aggiorna',audit:'Registro',deleteAll:'Elimina tutto',confirmDelete:'Eliminare?',yes:'Sì',no:'No',newChat:'Nuova chat',creative:'Creativo',faithful:'Fedele',instant:'Istantaneo',full:'Completo',aspect:'Rapporto d\\'aspetto',portrait:'Ritratto',landscape:'Paesaggio',square:'Quadrato',custom:'Personalizzato',durasi:'Durata',tokens:'Crediti',translate:'Tradurre?',enhance:'Migliora',addLora:'Aggiungi LoRA',remove:'Rimuovi',weight:'Peso',triggerWords:'Parole Trigger',noTrigger:'Nessun trigger',vae:'VAE',auto:'Automatico',defaultValue:'Predefinito',pcOnly:'Solo PC',mobileOnly:'Solo Mobile',desktopMobile:'Desktop e Mobile',collapse:'Comprimi',expand:'Espandi',pasteData:'Incolla dati',presets:'Preimpostazioni',reset:'Reimposta',models:'Modelli',addEmbedding:'Aggiungi Embedding',addControlNet:'Aggiungi ControlNet',negativeShort:'Negativo',oneImage:'1 immagine',samplerLabel:'Sampler',schedulerLabel:'Scheduler',noLora:'Nessuna LoRA',noTriggerWords:'Nessuna parola trigger'}
};`;

// Replace the old T object
const tStart = c.indexOf('var T={');
const tEnd = c.indexOf('};', tStart) + 2;
if (tStart > -1 && tEnd > tStart) {
  c = c.substring(0, tStart) + newT + c.substring(tEnd);
  console.log('T object replaced successfully');
}

// Step 2: Add data-t attributes to HTML elements
const replacements = [
  // Models header
  ['<span class="text-sm font-semibold">Models</span>', '<span class="text-sm font-semibold" data-t="models">Models</span>'],
  // Add LoRA/Embedding buttons
  ['<button id="btn-addlora" class="btn btn-ghost flex-1 h-9 border bd text-xs">Add LoRA</button>', '<button id="btn-addlora" class="btn btn-ghost flex-1 h-9 border bd text-xs" data-t="addLora">Add LoRA</button>'],
  ['<button class="btn btn-ghost flex-1 h-9 border bd text-xs">Add Embedding</button>', '<button class="btn btn-ghost flex-1 h-9 border bd text-xs" data-t="addEmbedding">Add Embedding</button>'],
  // Add ControlNet
  ['<button class="btn btn-ghost w-full h-9 border bd text-xs">Add ControlNet</button>', '<button class="btn btn-ghost w-full h-9 border bd text-xs" data-t="addControlNet">Add ControlNet</button>'],
  // LoRA header
  ['<span class="text-sm font-semibold">LoRA</span>', '<span class="text-sm font-semibold" data-t="addLora">LoRA</span>'],
  // Trigger Words header
  ['<span class="text-sm font-semibold">Trigger Words</span>', '<span class="text-sm font-semibold" data-t="triggerWords">Trigger Words</span>'],
  // Negative checkbox
  ['<span class="text-xs text-neutral-400">Negative</span>', '<span class="text-xs text-neutral-400" data-t="negativeShort">Negative</span>'],
  // Paste/Presets/Reset buttons
  ['<button class="btn btn-ghost w-full h-9 justify-between"><span>Paste Generation Data</span>', '<button class="btn btn-ghost w-full h-9 justify-between"><span data-t="pasteData">Paste Generation Data</span>'],
  ['<button class="btn btn-ghost w-full h-9 justify-between"><span>Presets</span>', '<button class="btn btn-ghost w-full h-9 justify-between"><span data-t="presets">Presets</span>'],
  ['<button class="btn btn-ghost w-full h-9 justify-between"><span>Reset</span>', '<button class="btn btn-ghost w-full h-9 justify-between"><span data-t="reset">Reset</span>'],
  // Prompt placeholder
  ['placeholder="Jelaskan apa yang ingin kamu buat..."', 'placeholder="Jelaskan apa yang ingin kamu buat..." data-t-placeholder="prompt"'],
  // Negative placeholder
  ['placeholder="Negative prompt..."', 'placeholder="Negative prompt..." data-t-placeholder="negative"'],
];

for (const [old, rep] of replacements) {
  if (c.includes(old)) {
    c = c.replace(old, rep);
    console.log('Replaced:', old.substring(0, 40) + '...');
  } else {
    console.log('NOT FOUND:', old.substring(0, 40) + '...');
  }
}

// Step 3: Update applyLang to handle placeholders
const oldApplyLang = 'function applyLang(){ document.querySelectorAll(\'[data-t]\').forEach(function(el){ var k=el.getAttribute(\'data-t\'); if(k) el.textContent=t(k); }); }';
const newApplyLang = `function applyLang(){
  document.querySelectorAll('[data-t]').forEach(function(el){ var k=el.getAttribute('data-t'); if(k) el.textContent=t(k); });
  document.querySelectorAll('[data-t-placeholder]').forEach(function(el){ var k=el.getAttribute('data-t-placeholder'); if(k) el.placeholder=t(k); });
  var promptEl=$('prompt'); if(promptEl) promptEl.placeholder=t('prompt');
  var negEl=$('negprompt'); if(negEl) negEl.placeholder=t('negative');
}`;
if (c.includes(oldApplyLang)) {
  c = c.replace(oldApplyLang, newApplyLang);
  console.log('applyLang updated');
}

writeFileSync('index.html', c);
console.log('Done!');
